name: egmn-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - scipy
  - matplotlib
  - numpy
  - numba
  - scikit-learn
  - pandas
  - sympy
  - ipympl
  - jupyter
  - jupyterlab
  - jupyter-book
  - jupytext
  - notebook
  - pre-commit
  - ruff
  - nodejs
  - mystmd
  - pip
  - pip:
      - git+https://github.com/alanlujan91/HARK@map_coordinates
      - ConSav
      - EconModel
      - black[jupyter]
